# Generated by Django 2.2.14 on 2021-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('SND', 'SUNDAES'), ('WFF', 'WAFFLES'), ('CRP', 'CREPES'), ('COK', 'COOKIES'), ('CKS', 'CAKES'), ('MLK', 'MILKSHAKES')], max_length=3)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
