# Generated by Django 2.2.14 on 2021-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SND', 'SUNDAES'), ('WFF', 'WAFFLES'), ('CRP', 'CREPES'), ('CHK', 'CHEESECAKE'), ('CKS', 'CAKES'), ('MLK', 'MILKSHAKES')], max_length=2)),
            ],
        ),
    ]
