# Generated by Django 2.2.14 on 2021-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SND', 'SUNDAES'), ('WFF', 'WAFFLES'), ('CRP', 'CREPES'), ('CHK', 'CHEESECAKE'), ('CKS', 'CAKES'), ('MLK', 'MILKSHAKES')], max_length=20),
        ),
    ]
