# Generated by Django 2.2.14 on 2021-02-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210223_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SN', 'SUNDAES'), ('WF', 'WAFFLES'), ('CP', 'CREPES'), ('CK', 'CHEESECAKE'), ('CS', 'CAKES'), ('MK', 'MILKSHAKES')], max_length=2),
        ),
    ]
