# Generated by Django 2.2.14 on 2021-02-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address1',
            new_name='apartment_address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address2',
            new_name='street_address',
        ),
    ]
