# Generated by Django 2.2.14 on 2021-02-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='one_click_purchase',
        ),
    ]
